%
% Test of the arcmakemenu system, where I look at the creation of a
% SuperNEC menu system. 

% Establish figure and handle storage.
CFh = figure;
set(CFh, 'MenuBar', 'none');
set(CFh, 'ToolBar', 'figure');
ud = get (CFh, 'UserData');
ud.handle.menu=[];
set (CFh, 'UserData',ud);

% Can either do this as an entire menu system at once, or in little bits: a
% hierarchy-at-a-time etc etc. Callback can be to the same file, or a
% special cb file...
menu={...
  '&File',...
  '>&Open',...
  '>>&Data_File...',...
  '>>&Output_File...',...
  '>&Save^s',...
  '>---',...
  '>E&xit^q',...
  ...
  '&Edit',...
  '>Vowels',...
  '>Consonants',...
  '>---',...
  '>Rot13',...
};

ud.handle.menu = arcmakemenu(CFh,'TESTarcmakemenuCB;',menu);

% And again :-)
menu={...
  '&Options',...
  '>Type',...
    '>>&Rectangular',...
    '>>&Polar',...
    '>>&Smith_Chart',...
  '>Reference',...
    '>>dBm',...
    '>>dBuV',...
    '>>W(linear)',...
  '>Zo',...
    '>>50_Ohm',...
    '>>75_Ohm',...
    '>>Other...',...
};
handles = arcmakemenu(CFh, 'TESTarcmakemenuCB;', menu);
ud.handle.menu = [ud.handle.menu, handles];

% Set initial menu state...
myhandle=findobj(ud.handle.menu, 'flat', 'Tag', 'Edit')
set (myhandle, 'Enable', 'Off'); % Grey out until we open a file.

myhandle=findobj(ud.handle.menu, 'flat', 'Tag', 'File.Save');
set (myhandle, 'Enable', 'Off');

% Yes, I know it doesn't make sense, its a demo :-)
myhandle = findobj (ud.handle.menu, 'flat', 'Tag',
  'Options.Type.Smith_Chart');
default=myhandle;  
myhandle = findobj (ud.handle.menu, 'flat', 'Tag',
  'Options.Reference.dBm');
default(end+1)=myhandle;  
myhandle = findobj (ud.handle.menu, 'flat', 'Tag',
  'Options.Zo.50_Ohm');
default(end+1)=myhandle;  
set (default, 'Checked', 'On');




set (CFh, 'UserData',ud);
